version: '3.8'
services:
  mentor-client:
    container_name: mentor-client
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
  cypress:
    container_name: cypress
    depends_on:
      - mentor-client
    build:
      context: cypress
    environment:
      - "CYPRESS_BASE_URL=http://mentor-client:3000"
      - "CYPRESS_SNAPSHOT_DIFF_DIR=/app/cypress/snapshots/snapshot_failed_diffs"
