version: '3.8'
services:
  client:
    container_name: mentor-client
    build:
      context: .
      dockerfile: ./docker/Dockerfile
  cypress:
    container_name: cypress
    depends_on:
      - client
    build:
      context: cypress
    environment:
      - "CYPRESS_BASE_URL=http://client/chat"
